Update build-kernel-feat-kernelsu.yml

diff --git a/.github/workflows/build-kernel-feat-kernelsu.yml b/.github/workflows/build-kernel-feat-kernelsu.yml
--- a/.github/workflows/build-kernel-feat-kernelsu.yml
+++ b/.github/workflows/build-kernel-feat-kernelsu.yml
@@ -1,5 +1,7 @@
 name: 构建KSU适配内核(随内核源码更新)
 on:
+  schedule:
+    - cron: '30 18 * * 0,1,3,6'
   workflow_dispatch:
      inputs:
       KERNEL_SOURCE:
@@ -27,7 +29,7 @@ jobs:
     - uses: actions/checkout@v3
     - name: Setup Configuration
       run: |
-        if [ $(cat config.env | grep "USE_CONFIG" | head -n 1 | cut -d "=" -f 2) = true ];then
+        if [ $(cat config.env | grep "USE_CONFIG_c" | head -n 1 | cut -d "=" -f 2) = true ];then
             echo "KERNEL_SOURCE=$(cat config.env | grep "KERNEL_SOURCE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
             echo "KERNEL_SOURCE_BRANCH=$(cat config.env | grep "KERNEL_SOURCE_BRANCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
             echo "KERNEL_DEFCONFIG=$(cat config.env | grep "KERNEL_DEFCONFIG" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
@@ -57,6 +59,31 @@ jobs:
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace
         git clone ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} android-kernel --depth=1
+    - name: Setup KernelSU
+      run: |
+        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernelset -eux
+        GKI_ROOT=$(pwd)
+        echo "[+] GKI_ROOT: $GKI_ROOT"
+        if test -d "$GKI_ROOT/common/drivers"; then
+            DRIVER_DIR="$GKI_ROOT/common/drivers"
+        elif test -d "$GKI_ROOT/drivers"; then
+            DRIVER_DIR="$GKI_ROOT/drivers"
+        else
+            echo '[ERROR] "drivers/" directory is not found.'
+            echo '[+] You should modify this scrpit by yourself.'
+        fi
+        test -d "$GKI_ROOT/KernelSU" || git clone https://github.com/tiann/KernelSU
+        cd "$GKI_ROOT/KernelSU"
+        git stash && git pull
+        cd "$GKI_ROOT"
+        echo "[+] GKI_ROOT: $GKI_ROOT"
+        echo "[+] Copy kernel su driver to $DRIVER_DIR"
+        cp -rf "$GKI_ROOT/KernelSU/kernel" "$DRIVER_DIR/kernelsu"
+        echo '[+] Add kernel su driver to Makefile'
+        DRIVER_MAKEFILE=$DRIVER_DIR/Makefile
+        grep -q "kernelsu" "$DRIVER_MAKEFILE" || echo "obj-y += kernelsu/" >>"$DRIVER_MAKEFILE"
+        echo '[+] Done.'
+        echo "ANYKERNELNAME=-KernelSU" >> $GITHUB_ENV
     - name: Build kernel
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
